<a href="https://colab.research.google.com/github/BadrinathMJ/Application-/blob/main/TF2_0_RNN_Shapes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.layers import Input, SimpleRNN, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#Things should automatically know and memorized
#N = No. of samples
#T = Sequence length
#D = No. of input features
#M = No.of hidden units
#K = No. of Output units

In [4]:
#Make some data
N = 1
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)
X

array([[[-0.4542045 , -0.39104127, -0.84341989],
        [ 0.29746081,  0.39041069,  0.60785902],
        [-0.45485051, -0.52576543,  0.85366667],
        [ 1.25473259, -0.91809292, -1.41549871],
        [ 0.0100051 , -0.88152353,  2.4606324 ],
        [ 0.5888898 , -0.21186489, -0.96697976],
        [-0.69796078, -0.56307342, -0.13280344],
        [-1.40579881, -0.44145948,  0.75535158],
        [-1.35634755,  0.79801962, -1.37966186],
        [-0.01658645, -0.5274032 ,  0.4191787 ]]])

In [5]:
#Make RNN
M = 5 #no. of hidden units
i = Input(shape=(T, D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i, x)

In [6]:
#Get the output
Yhat = model.predict(X)
print(Yhat)

1/1 [==============================] - 0s 313ms/step
[[0.6125359 0.6098406]]


In [7]:
#see if we can replicate this output 
#get the weight first
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 10, 3)]           0         
                                                                 
 simple_rnn (SimpleRNN)      (None, 5)                 45        
                                                                 
 dense (Dense)               (None, 2)                 12        
                                                                 
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [8]:
#see what returned 
model.layers[1].get_weights()

[array([[ 0.61692935,  0.4360308 ,  0.43290776, -0.18513823,  0.5667537 ],
        [ 0.28621405,  0.8069555 , -0.72557175,  0.48048264,  0.27312177],
        [ 0.24212307,  0.8333524 , -0.7363907 , -0.46401185, -0.6086836 ]],
       dtype=float32),
 array([[ 0.06796098, -0.937704  , -0.17892559,  0.19253483,  0.2168143 ],
        [ 0.20754704,  0.26563764,  0.18312994,  0.6225068 ,  0.682136  ],
        [-0.22173153, -0.20847172,  0.8923313 ,  0.19591254, -0.26969963],
        [-0.3897642 , -0.04901618,  0.22190598, -0.6189326 ,  0.642932  ],
        [-0.86673206,  0.06545794, -0.29824772,  0.3923728 , -0.03978248]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [9]:
#check their shapes 
#should make sense 
#First output id input>hidden
#second output is hidden > hidden
#Third output id bias term vector length of M
a, b, c = model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)

(3, 5) (5, 5) (5,)


In [10]:
Wx, Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [13]:
h_last = np.zeros(M)  #initial hidden state
x = X[0]  #the one and only one sample
Yhats = []  #where we store the outputs

for t in range(T):
  h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
  y = h.dot(Wo) + bo # We only care about this value on the last iteration
  Yhats.append(y)

  #important assign h to h_last
  h_last = h

#print the final output
print(Yhats[-1])

[0.61253575 0.60984049]
